### ISSUE TITLE
Request body ambiguity

### ISSUE THREAD

**Issue by Billyblbl** [MatthieuMv/openZia#5]
As `HTTP::Request` doesn't contain `getBody()` methods, modules currently need to look for the request body in Packet's `ByteArray`. However, the API does not explicitly enforce if HTTP parser modules implementations should remove the data they use from this `ByteArray` to build the method, URI & headers of the `HTTP::Request`, or just translate it without touching the `ByteArray`.

This leaves post-parser modules with no guaranty around whether the `ByteArray` of `Packet` is left with the body of the request or with all the data of the Packet, and as such post-parser modules need to be coupled in terms of behavior with an appropriate implementation of an HTTP parser module

This could be fixed by enforcing one way in the specs of the API (for convenience's purpose, enforcing the HTTP parsers to remove parsed data seems like the best way in this case), or by providing `getBody()` methods to `HTTP::Request`, so that HTTP parser can simply build the body 
directly in the `HTTP::Request` from the `ByteArray`

**Comment by MatthieuMv** [comment]
The changes are done but I didn't took your pull request as I wanted to rewrite a base class for both Request and Response.
The HTTP::Request has now a getBody() function in addition of the getURI().
Please note that this was a dumb mistake of mine, as I didn't see that HTTP responses could have an URI **AND** a body message, as explained in [this website](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages).

Please note that you are **NOT** intended (for performances issues) to modify the ByteArray.
The expected implementation is to simply parse it and directly set **Context's HTTP::Request** while doing so.
However I chose to let you the choice of resources management so you can implement it any way you feel it.

In fact, even this setup has performances troubles but I had to choose between performances and simplicity for HTTP structures (and I chose simplicity).
This reason is why I highly recommend you to implement a cache, as described at the end of [Context's documentation](https://github.com/MatthieuMv/openZia/blob/master/CONTEXT.md).

Anyway, thank you for your help !
